spring:
  datasource:
    url: "jdbc:postgresql://ep-noisy-river-amffk4qw.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require"
    username: "neondb_owner"
    password: "npg_IwKdvc1ubRg2"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug