server:
  port: 8080

spring:
  profiles:
    active: dev

app:
  security:
    jwt:
      issuer: flowforge
      accessTokenMinutes: 15
      refreshTokenDays: 14
      secret: ${APP_JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html