server:
  port: 8080

spring:
  profiles:
    active: dev

app:
  security:
    jwt:
      issuer: flowforge
      accessTokenMinutes: 15
      refreshTokenDays: 14
      secret: "flowforge-dev-secret-key-flowforge-dev-secret-key-123456"

springdoc:
  swagger-ui:
    path: /swagger-ui.html